# Generated by Django 5.0.4 on 2024-04-20 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_manager", "0002_fol"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fol",
        ),
    ]
