# Generated by Django 5.0.4 on 2024-04-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_manager", "0003_delete_fol"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="files",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="file_manager.file",
            ),
        ),
    ]
