# Generated by Django 5.0.4 on 2024-04-21 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_manager", "0004_folder_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="files",
        ),
    ]
