# Generated by Django 5.0.4 on 2024-04-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_manager", "0005_remove_folder_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="files",
            field=models.ManyToManyField(
                blank=True, related_name="present_files", to="file_manager.file"
            ),
        ),
    ]
